import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, ThinkingLevel } from "@google/genai";
import * as dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '10mb' }));

// Initialize Gemini
const ai = new GoogleGenAI({ 
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// API Routes
app.post("/api/chat", async (req, res) => {
  try {
    const { messages, systemInstruction } = req.body;
    
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    
    try {
      const responseStream = await ai.models.generateContentStream({
        model: "gemini-2.0-flash-lite",
        contents: messages,
        config: {
          systemInstruction: systemInstruction || "You are a helpful writing assistant for a book editor called Inkwell Studio. You can suggest snippets and critique content.",
          thinkingConfig: { thinkingLevel: ThinkingLevel.LOW },
          tools: [{ googleSearch: {} }],
        },
      });

      for await (const chunk of responseStream) {
        const payload = JSON.stringify({
          text: chunk.text || "",
          thoughts: "" 
        });
        res.write(`data: ${payload}\n\n`);
      }
      res.write(`data: [DONE]\n\n`);
      res.end();
    } catch (apiError: any) {
      if (apiError.message?.includes('429') || apiError.message?.includes('RESOURCE_EXHAUSTED')) {
        console.log("Falling back to OpenRouter for Chat Stream");
        
        const openRouterMessages = [];
        if (systemInstruction) {
          openRouterMessages.push({ role: "system", content: systemInstruction });
        }
        for (const m of messages) {
          openRouterMessages.push({ role: m.role === 'model' ? 'assistant' : 'user', content: m.parts[0].text });
        }

        const orResponse = await fetch("https://openrouter.ai/api/v1/chat/completions", {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${process.env.OPENROUTER_API_KEY || 'OPENROUTER_API_KEY'}`,
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            model: "openrouter/free",
            messages: openRouterMessages,
            service_tier: "flex",
            stream: true
          })
        });
        
        if (!orResponse.ok) {
           throw new Error("OpenRouter error: " + orResponse.statusText);
        }
        
        if (!orResponse.body) {
           res.write(`data: [DONE]\n\n`);
           return res.end();
        }

        const reader = orResponse.body.getReader();
        const decoder = new TextDecoder();
        let buffer = '';
        
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          
          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split('\n');
          buffer = lines.pop() || '';
          
          for (const line of lines) {
            if (line.startsWith('data: ')) {
              if (line.includes('[DONE]')) continue;
              try {
                const parsed = JSON.parse(line.slice(6));
                const textChunk = parsed.choices?.[0]?.delta?.content || "";
                if (textChunk) {
                  res.write(`data: ${JSON.stringify({ text: textChunk, thoughts: "" })}\n\n`);
                }
              } catch (e) {}
            }
          }
        }
        res.write(`data: [DONE]\n\n`);
        res.end();
      } else {
        throw apiError;
      }
    }
  } catch (error: any) {
    console.error("Chat Error:", error);
    res.write(`data: {"error": ${JSON.stringify(error.message)}}\n\n`);
    res.write(`data: [DONE]\n\n`);
    res.end();
  }
});

app.post("/api/generate-image", async (req, res) => {
  try {
    const { prompt, aspectRatio = "1:1" } = req.body;
    
    try {
      const response = await ai.models.generateContent({
        model: 'gemini-2.0-flash',
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          maxOutputTokens: 2048,
        }
      });

      let imageUrl = "";
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }

      if (!imageUrl) {
        // Check if it returned a text URL or markdown
        const text = response.candidates?.[0]?.content?.parts?.[0]?.text || "";
        const match = text.match(/https?:\/\/[^\s)]+/);
        if (match) imageUrl = match[0];
      }

      if (!imageUrl) {
        throw new Error("No image generated by model");
      }

      res.json({ imageUrl });
    } catch (apiError: any) {
      if (apiError.message?.includes('429') || apiError.message?.includes('RESOURCE_EXHAUSTED') || apiError.message?.includes('402')) {
        console.log("Falling back to OpenRouter for Image Gen");
        
        const orResponse = await fetch("https://openrouter.ai/api/v1/chat/completions", {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${process.env.OPENROUTER_API_KEY || 'OPENROUTER_API_KEY'}`,
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            model: "google/gemini-2.0-flash-001",
            messages: [
              { role: "user", content: prompt }
            ],
            max_tokens: 1024,
            service_tier: "flex"
          })
        });

        const orData = await orResponse.json();
        if (orData.error) throw new Error("OpenRouter " + JSON.stringify(orData.error));

        // Note: OpenRouter may return image as text markdown or data url if it supports generative image calls
        const reply = orData.choices?.[0]?.message?.content || "";
        res.json({ imageUrl: reply });
      } else {
        throw apiError;
      }
    }
  } catch (error: any) {
    console.error("Image Gen Error:", error);
    res.status(500).json({ error: error.message });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
